### ISSUE TITLE
Remove expect depency

### ISSUE THREAD

**Issue by esamattis** [VanCoding/NodeSSH#4]
You can use  [pty.js](https://github.com/chjj/pty.js/) to send the password.

Example: http://stackoverflow.com/a/9788213/153718

**Comment by VanCoding** [comment]
pty.js is definately the better way to do it, but to be honest, one does not need NodeSSH anymore with pty.js. We better keep NodeSSH as an alternative to it.

If someone wants to do it with pty.js, which is recommended, the person can do it direct with pty.js and needs no library in between.

**Comment by esamattis** [comment]
That's pretty much true :)

Just wanted to let you know.
