### ISSUE TITLE
License is missing.

### ISSUE THREAD

**Issue by gwdp** [VanCoding/NodeSSH#5]
License file is missing. What license it's on ?

**Comment by VanCoding** [comment]
Oh, well... I did it just for fun. You can do with it whatever you want
withouth any restrictions. You can take any license that fits you best ;)

2012/7/31 Gabriel Pacheco <
reply@reply.github.com

**Comment by gwdp** [comment]
MIT Added on my branch ! 
Thanks for it...

**Comment by VanCoding** [comment]
You're welcome ;)

2012/7/31 Gabriel Pacheco <
reply@reply.github.com
